//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmericanAnswers
    {
        public int Id { get; set; }
        public int NumQuestion { get; set; }
        public int Answers { get; set; }
        public bool IsTrue { get; set; }
    
        public virtual Questions1 Questions1 { get; set; }
    }
}
