//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstyfridmanMathTestEntities : DbContext
    {
        public EstyfridmanMathTestEntities()
            : base("name=EstyfridmanMathTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AmericanAnswers> AmericanAnswers { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<Questions1> Questions1 { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
